FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Install nodemon globally
RUN apt-get update && apt-get install -y npm && npm install -g nodemon

# Command to run the application with nodemon
CMD ["nodemon", "--config", "nodemon.json"]
